---
#ITA
#Seleziona i mondi in cui vuoi che KillHealth funzioni
#
#ENG
#Select the worlds where you want KillHealth to work
worlds:
  - Test123
#ITA
#killer-message: è il messaggio che viene mandato al player
#death-message: è il messaggio che viene mandato a tutto il server
#Questi sono i messaggi che appariranno alla morte del player:
#{player} è il nome del player,
#{killername} è il nome del player che uccide
#
#ENG
#killer-message: is the message that is sent to the player
#death-message: is the message that is sent to the whole server
#These are the messages that will appear when a player dies:
#{player} is the name of the player,
#{killername} is the name of the player who kills
killer-message: "{killername} killed {player} and you got healed!"
death-message: "{player} was killed by {killername}"
...