---
#ITA
#Seleziona i mondi in cui vuoi che KillHealth funzioni
#
#ENG
#Select the worlds where you want KillHealth to work
worlds:
  - pvp
  
#ENG
#killer-message: is the message that is sent to the player
#death-message: is the message that is sent to the whole server
#These are the messages that will appear when a player dies:
#{player} is the name of the player,
#{killername} is the name of the player who kills
killer-message: "§6Killed §f{player}! §l+8§r§6 Coins"
death-message: "§7You were slain by §c{killername}"
...
